### ISSUE TITLE
Add transaction around the migration 

### ISSUE THREAD

**Issue by elpete** [coldbox-modules/cfmigrations#1]
A migration can contain any number of SQL statements. Right now, if one of the statements fail, any previous statements that executed successfully are not rolled back. This leaves the database is a state that the migration is not expected and cannot rollback. 

We should add a transaction around the migration function to prevent this issue.

**Comment by elpete** [comment]
One issue with this approach is not all vendors support transactions with DDL statements.

We can either:
1. Ignore those vendors
2. Do some sort of snapshot before running the migration and restore the snapshot if anything goes wrong
Number 2 seems sort of expensive since we'd need to both generate and apply the snapshot, potentially.

**Comment by DiscountDarcy** [comment]
I vote for door #1.
