### ISSUE TITLE
Multiple datasources

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/cfmigrations#12]
Hello - this module looks very promising.  Our application has 3 datasources - main (ui/billing/etc), logging (where devices send their data) and alerts.  I would like to use cfmigrations to keep them all up to date.  How do I set up the environment variables so that migrate install works?  Any other "gotcha's" to be aware of?

**Comment by elpete** [comment]
Currently, the table for `cfmigrations` is only stored in one database, the one defined in your `box.json`.  You can have your migrations run against any datasource by specifying the datasource in the options (either `queryExecute` or the equivalent `SchemaBuilder` commands).

There is discussion to support multiple datasources for storing the `cfmigrations`, but it currently has some gaps to fill.
