### ISSUE TITLE
Cannot find migration cfc paths in Windows environment

### ISSUE THREAD

**Issue by GaryStanton** [coldbox-modules/cfmigrations#16]
The latest version of Wirebox is unable to parse a full Windows file path due to a check in the injector that dumps out a blank string when passed anything with a `:` character. https://github.com/Ortus-Solutions/commandbox/blob/8d12ac9b13b7ff95af4cd1f7b5bac7a92785ddc6/src/cfml/system/wirebox/system/ioc/Injector.cfc#L542

The `findAll()` function at https://github.com/coldbox-modules/cfmigrations/blob/7a0d7ab8567b076383ef54256287555f0eac127c/models/MigrationService.cfc#L66 is using a `directoryList` call to retrieve a list of migration cfcs, and while it seems to attempt to generate a relative path at one point on line 97, when run inside CommandBox at least, the working directory is not the same and the resulting component path is invalid.

Wirebox then errors out when running `migrate up`.

**Comment by GaryStanton** [comment]
Full discusion here: https://cfml.slack.com/archives/C06TSRXCJ/p1585618307087700

**Comment by elpete** [comment]
This seems to be an issue specifically with commandbox-migrations.  Closing the issue here in favor of the https://github.com/commandbox-modules/commandbox-migrations/issues/14
