### ISSUE TITLE
Add Multi-Tenant Support

### ISSUE THREAD

**Issue by micahknox** [coldbox-modules/cfmigrations#2]
It would be awesome if you could define an array of datasources in the configuration of the module and each of these datasources would get the migration operations applied to it. We have a multi-tenant application where the database for each tenant needs to be migrated with each release and this is the only thing keeping us from using the tool. Would we love to start using it if this is something that could be easily added.

**Comment by elpete** [comment]
That’s an interesting idea. Do you have a suggestion for the syntax? I think you could do this right now by looping over your datasources and passing it to the `queryExecute`. If you are using `qb`’s `SchemaBuilder` I think that would need to be added. If you are using `commandbox-migrations` then there is more work to do to load the datasources. Suggestions?

**Comment by micahknox** [comment]
@elpete I thought about looping over the datasources and passing it to `queryExecute` but the problem is that the service above the migrations is responsible for keeping track of which ones were executed against a database so that piece would need to keep track of each tenant individually. As far as syntax, it seems like it would fit into the either the moduleConfig or the environment settings, depending on how you were using it. An array of datasource structures seems like the simplest approach.

**Comment by elpete** [comment]
Good point about the `cfmigrations` table.  Can I ask how you are running these migrations right now?  That might help show a good syntax for running this against multiple datasources.

**Comment by micahknox** [comment]
Currently we write TSQL scripts for each release and create a new database version in a code repo. When we are ready to release, we open the release script in a tool called SQL Mult-Script, and run it against each individual database. We do not track the migrations in the database at this point.

**Comment by elpete** [comment]
Closed by #28 in v3.0.0
