### ISSUE TITLE
cfmigration can check if .env or cfconfig has a datasource already created if it has then use that one

### ISSUE THREAD

**Issue by BalbinoOrtus** [coldbox-modules/cfmigrations#36]
right now cfmigrations only checks its own config if the datasource exists, but normally there is already a datasource in the .env or cfconfig, it would be nice if it checked and only if it does not find any datasource then error out.

**Comment by elpete** [comment]
Can you give me an example?  Are you talking about the config file that can accept a `datasource`? The config property is optional.

**Comment by BalbinoOrtus** [comment]
last year we had an error trying to set up cf migrations, where i had already a datasource but still the cf migration did not connect when doing migrate init, but i remember that installing the commandbox-dotenv fixed it, i even added it in a walkthrough i made, is the dotenv a dependency of cfmigrations?

**Comment by elpete** [comment]
Hmmm...I'm not sure. If you can show me an example I can take another look.
