### ISSUE TITLE
Please change QB to provider

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/cfmigrations#37]
I use QB in provider mode everywhere.  In migrations, I get bit because I forget to use `newQuery()` when creating and populating multiple tables (usually lookups - states, countries, tax rates, etc).  Changing the QB injection to be a provider would still allow old code using `newQuery()` to operate as normal while alleviating this problem.

**Comment by elpete** [comment]
While I understand the frustration, doing so would introduce unnecessary extra objects and WireBox calls in instances where people _don't_ want a provider.  For instance, I occasionally will use `getInstance( "QueryBuilder@qb" )` right in my handler calls.  I don't want that to be taxed with an extra WireBox call.  We could introduce a new injection, but it would basically just wrap providers.
