### ISSUE TITLE
Cfmigration table detected in all available schemes instead of current database

### ISSUE THREAD

**Issue by wpdebruin** [coldbox-modules/cfmigrations#8]
Ok, I just tested this in MySQL
the point is compileTableExists fires this query
`SELECT 1 FROM` information_schema`.`tables` WHERE `table_name` = 'cfmigrations'`
if Laur and you are both using the same credentials for your databases you will indeed see each others db. If you would use separate credentials for each db, which is more secure anyway, you will not have this problem

elpete [4:53 PM]
qb doesn’t see the connection string. It just uses it. There _may_ be a way to get it from Java, but I think the easier path is to have `hasTable` take an optional `schema` parameter.

**Comment by cvonstetten** [comment]
I'm going to hazard a guess that the same issue will apply to MS SQL, but I haven't verified this.

**Comment by elpete** [comment]
This is solved by providing a `schema` to the `MigrationService`.
